### ISSUE TITLE
【Main】【modbus rtu】串口模式下没有将连接模式 connection_mode字段成功隐藏

### ISSUE THREAD

**Issue by Jimmy-Wen** [emqx/neuron#1356]
![1687744681903](https://github.com/emqx/neuron/assets/44196699/a5de9ed9-5cea-47ff-b859-d2d3bb76e6cb)
v2.4.7以后主线版本均存在此现象，不影响正常功能

**Comment by gc87** [comment]
Yes, we will fix it, thanks!
