### ISSUE TITLE
从北向mqtt做南向的反控支持吗？/neuron/mqttzf/write/req 里面该怎么传参呢？哪里有技术交流群？

### ISSUE THREAD

**Issue by yeah1** [emqx/neuron#1365]
# Issue Template

Please fill in the issue as required.

* System:
* Architecture:
* Version:
* Problem Description:
* Log Information:

**Comment by gc87** [comment]
Yes, it's a basic capability of neuron, check the documentation for details, here's the [documentation link](https://neugates.io/docs/en/latest/configuration/north-apps/mqtt/api.html#data-upload).

**Comment by gc87** [comment]
You can email your wechat account to chun.gao@emqx.io and I will invite you to join the technical discussion group.
