### ISSUE TITLE
【Main】【modbus】调试报文显示不全面

### ISSUE THREAD

**Issue by Jimmy-Wen** [emqx/neuron#1366]
modbus rtu已经连接，但配置不存在的tag，如图，主站使用03功能码进行读取，从站回复83 错误 功能码。 这种情况下，即使打开debug开关，从站回复的串口错误报文依然无法显示，在遇到问题时，这种情况不太方便进行定位

<img width="1140" alt="1688106864449" src="https://github.com/emqx/neuron/assets/44196699/506b67ee-26a3-485b-8859-aee389e3fc06">

**Comment by gc87** [comment]
OK, I'll give feedback and discuss whether it can be enhanced.
