### ISSUE TITLE
通道配置与节点配置可否分开独立配置

### ISSUE THREAD

**Issue by Jimmy-Wen** [emqx/neuron#1393]
当下，不论南向设备还是北向应用，通道配置信息（如网口的ip/port， 串口的波特率等）都依附于节点的属性配置。
在边缘设备上，通讯通道常见的有串口、网口、4G、WIFI、LORA、DI、DO、模拟量等等；
将通道先行配置，然后节点配置时直接选择已有通道，其他网关多是如此操作，这种配置模式可否借鉴？

**Comment by lixiumei123** [comment]
配置不同的驱动需要不同的参数，分两步配置似乎不是很好。

**Comment by Jimmy-Wen** [comment]
> 配置不同的驱动需要不同的参数，分两步配置似乎不是很好。
