### ISSUE TITLE
In the Modbus RTU base Ethernet server mode, when a read operation encounters no response, the connection gets reset and disconnects.

### ISSUE THREAD

**Issue by huanghe-1** [emqx/neuron#1602]
If multiple devices are connected to this server, and one read operation fails, the entire server connection resets and disconnects, which is not ideal. The expected behavior should be to skip past the failed read operation and proceed to read from the next device.

**Comment by hxy7yx** [comment]
> If multiple devices are connected to this server, and one read operation fails, the entire server connection resets and disconnects, which is not ideal. The expected behavior should be to skip past the failed read operation and proceed to read from the next device.

Yes, it will be changed to not reconnect when data cannot be received.

**Comment by hxy7yx** [comment]
(https://github.com/emqx/neuron/pull/1648)
