### ISSUE TITLE
self compile application put to other machine,can't be run correctly,report missing libasan.so.5

### ISSUE THREAD

**Issue by huanghe-1** [emqx/neuron#1770]
at the complie machine,run correctly,copy to other machine ,it 's wrong, but ,at the some machine ,download version from  official website，run correctly,don't report error.

**Comment by hxy7yx** [comment]
If libasan is missing, install libasan, or alternatively, compile without enabling asan.

**Comment by huanghe-1** [comment]
you means  official download version compile  without enabling asan? so it be run correctly not report missing libasan.so.5.

**Comment by hxy7yx** [comment]
yes

**Comment by huanghe-1** [comment]
thanks.
