### ISSUE TITLE
centos7.8 docker run fail

### ISSUE THREAD

**Issue by gooker** [emqx/neuron#1851]
# Issue Template

Please fill in the issue as required.

* System: centos7.8  Docker version 25.0.3, build 4debf41
* Architecture:x64
* Version: 
* [root@localhost ~]# docker pull emqx/neuron:latest
latest: Pulling from emqx/neuron
8ee087424735: Pull complete 
2b2a234a18e2: Pull complete 
3cf8ccad4038: Pull complete 
5972ac9aebcf: Pull complete 
bf62dea805d6: Pull complete 
7635545c1983: Pull complete 
393f260d713d: Pull complete 
370af003bef3: Pull complete 
e94c16de716f: Pull complete 
3a5e90fcb535: Pull complete 
Digest: sha256:2aecd76900e63e863542c491db3f411b4cf29f2a13ebae0fd88dbe0efc9822c1
Status: Downloaded newer image for emqx/neuron:latest
docker.io/emqx/neuron:latest
* Problem Description:
* [root@localhost ~]# docker run  --name neuron --log-opt max-size=100m -p 7000:7000 --privileged=true -v /host/dir:/opt/neuron/persistence  --restart=always emqx/neuron:latest
./neuron: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
* Log Information:

**Comment by ZhouBox** [comment]
The recent release will resolve this issue.
