### ISSUE TITLE
Cannot display hardware identifier

### ISSUE THREAD

**Issue by wubibig** [emqx/neuron#1935]
Please fill in the issue as required.

* System: 22.04.1-Ubuntu
* Architecture: x86-64
* Version: 2.8.0
* Problem Description: Cannot display hardware identifier.
* Log Information:
[neuron.log](https://github.com/emqx/neuron/files/14845456/neuron.log)

![image](https://github.com/emqx/neuron/assets/41566591/c9d3eef4-a652-46a1-a22a-fa95d0ba552d)

![image](https://github.com/emqx/neuron/assets/41566591/aadd9927-2d04-4ed7-8552-5cc63eb1f2d4)

**Comment by ZhouBox** [comment]
What version of the dashboard are you using?

**Comment by ZhouBox** [comment]
What version of the dashboard are you using?

**Comment by ZhouBox** [comment]
What version of the dashboard are you using?

**Comment by wubibig** [comment]
Neuron Dashboard 2.6.3

**Comment by ZhouBox** [comment]
The version compiled from the source code does not support this API.
