### ISSUE TITLE
How to send MQTT at internals less than 100ms?

### ISSUE THREAD

**Issue by leo-leonardo** [emqx/neuron#2065]
# How to send MQTT collection message less than 100ms internal?

In neuron-dashboard, I try to increase the frequency sending MQTT message of South-Devices to MQTT broker. But when I set the `intenal=20ms`, an error message is shown to tell me the minimum of internal is 100.

Please tell me how to set the internal or where (or which file) I can modify the source code. Any tip might be helpful.

* System: Ubuntu 20.04

![image-20240603151625464](https://github.com/emqx/neuron/assets/54011134/ae3e1481-dc55-4fb9-b3af-561208cfbc90)

**Comment by fengzeroz** [comment]
The release version of the data frequency is limited to 100ms, you can modify the code to remove this limitation.

**Comment by leo-leonardo** [comment]
> The release version of the data frequency is limited to 100ms, you can modify the code to remove this limitation.

Thanks for your clue! I found the config value at `mqtt_client.h`.
