### ISSUE TITLE
The MQTT write operation on South Device is invalid.

### ISSUE THREAD

**Issue by leo-leonardo** [emqx/neuron#2115]
# The MQTT write operation on South Device is invalid.

When I try to overwrite value on my tag, I send the MQTT message to the neuron write topic. But, the message seems not received by neuron, the value is not write to the tag.
![image](https://github.com/emqx/neuron/assets/54011134/8cf102ef-5556-472f-9ccf-764a1c569a45)

The topic name is checked.
![image](https://github.com/emqx/neuron/assets/54011134/c9c056c9-9034-4978-9011-46ebf4ae02b2)

And the group and tag are also checked.
![image](https://github.com/emqx/neuron/assets/54011134/6682f4a0-763c-4fb3-86a2-626eaf1a7913)

The subscription data is captured correctly.
![image](https://github.com/emqx/neuron/assets/54011134/150979b4-429f-4c54-8b71-ccc70b9e8b52)

**Did I miss any configuration? I have controlled successfully in the `apt` installed version, but this trouble happened in the compiled version.**

**Comment by eeff** [comment]
@leo-leonardo make sure the broker which the mqtt plugin connects is exactly the broker you publish the write requests. If that's the case and you are still not able to write the tag, please check the log of the mqtt plugin to find any clue of problem.

**Comment by leo-leonardo** [comment]
> @leo-leonardo make sure the broker which the mqtt plugin connects to is exactly the broker you publish the write requests. If that's the case and you are still not able to write the tag, please check the log of the mqtt plugin to find any clue of problem.

Thank you! I check the log and find that Neuron can not decode the MQTT message for the `'` I use. Now, `mosquitto_pub -t /topic -m '{"key":"value"}'` is success.
