### ISSUE TITLE
Is there a way to remove all node by http api?

### ISSUE THREAD

**Issue by bulabulabula818** [emqx/neuron#2183]
# Issue Template

Please fill in the issue as required.

* System:
* Architecture:
* Version:
* Problem Description:
* Log Information:

**Comment by hxy7yx** [comment]
At present, the API can only delete nodes one by one. What are the usage scenarios for deleting all nodes through the API?

**Comment by bulabulabula818** [comment]
emm, i want to remove all node by only one http api, then i will update my new node to neuron, but, anyway i choose to remove it one by one(ps:sometimes it response timeout, and now i cant find a proper way to handle it... XD)
