### ISSUE TITLE
How to fetch data in PLC address like %MW110.0 through ModbusTcp?

### ISSUE THREAD

**Issue by leo-leonardo** [emqx/neuron#2196]
# Issue Template

In my plc code demo, I have some variables:
![image](https://github.com/user-attachments/assets/5fa9e2d3-08a8-44d2-b560-c1ae0eeba0ab)

How can I get data when I only have these address? I tried 
![image](https://github.com/user-attachments/assets/a4847d81-a770-4095-a064-d366b959aac1)
and 
![image](https://github.com/user-attachments/assets/d57f5608-1894-46bf-beb6-2a6e65a0c30d)
but failed.

How can I transform the %MW address to integer address like 48960?

**Comment by fengzeroz** [comment]
What type of PLC is being used? Different models may have different rules for mapping PLC address to Modbus address.

**Comment by leo-leonardo** [comment]
> What type of PLC is being used? Different models may have different rules for mapping PLC address to Modbus address.

I am using Schneider Modicon TM172PBG18R PLC. Can I use this mapping rule to get Modbus address in other PLCs?

**Comment by fengzeroz** [comment]
> > What type of PLC is being used? Different models may have different rules for mapping PLC address to Modbus address.
> 
> I am using Schneider Modicon TM172PBG18R PLC. Can I use this mapping rule to get Modbus address in other PLCs?

Probably not. You should configure the tag address according to the documentation for this plc.

**Comment by leo-leonardo** [comment]
> > > What type of PLC is being used? Different models may have different rules for mapping PLC address to Modbus address.
> > 
> > 
> > I am using Schneider Modicon TM172PBG18R PLC. Can I use this mapping rule to get Modbus address in other PLCs?
> 
> Probably not. You should configure the tag address according to the documentation for this plc.
