### ISSUE TITLE
neu_plugin_op 高频次写入会导致内存泄漏。

### ISSUE THREAD

**Issue by a-jiang** [emqx/neuron#2333]
# Issue Template

我通过定时器开启一个写入操作，top 观察RES内存增长情况，发现半个小时左右内存有增长。
运行41分钟：
<img width="396" alt="1733128771927" src="https://github.com/user-attachments/assets/164c1a6c-5963-4c70-8176-fda5a06c7c61">
运行2个小时后：
<img width="389" alt="1733128802576" src="https://github.com/user-attachments/assets/548b9dbc-56cd-4403-a89b-046a7f2e6079">
write_test方法：
<img width="338" alt="d747e4d941e1607459ae4820ffd419e" src="https://github.com/user-attachments/assets/0b763647-9a67-4933-ae96-c5f12e4291b0">

调用neu_plugin_op 的方法：
<img width="350" alt="3923349eea6a0d3496d50469390d18a" src="https://github.com/user-attachments/assets/eee7da69-0ad7-45cb-8468-503ed0a4ab00">

* System:
* Architecture:
* Version:2.7
* Problem Description:
* Log Information:

**Comment by ZhouBox** [comment]
The Northbound app needs to implement the `request` interface to handle core messages. The `ctx` object for Northbound commands needs to be managed by the Northbound app itself.

**Comment by a-jiang** [comment]
> The Northbound app needs to implement the `request` interface to handle core messages. The `ctx` object for Northbound commands needs to be managed by the Northbound app itself.

Thanks for the reply. I set `ctx` to NULL and the memory has stabilized, but I keep running it for 12 hours and the memory will grow.
Adjusted code:
![image](https://github.com/user-attachments/assets/32a0d136-7352-4d35-8448-35947ab97287)
Memory change ( about 1 hour):
![image](https://github.com/user-attachments/assets/ac63a3af-ac92-432f-a34e-253a92b12be2)
Memory change ( about 12 hour):

**Comment by a-jiang** [comment]
> The Northbound app needs to implement the `request` interface to handle core messages. The `ctx` object for Northbound commands needs to be managed by the Northbound app itself.
我这边把ctx 调整后的代码如下：
<img width="305" alt="1733725769942" src="https://github.com/user-attachments/assets/c9a1c972-4324-426c-8192-82dc9232edfc">
写入频次调整为100ms 。
经过测试20分钟后，内存持续增长：
<img width="404" alt="1733725809966" src="https://github.com/user-attachments/assets/f95ee691-4643-432d-9474-23a0910d56c4">
27分钟后：
<img width="409" alt="1733726020674" src="https://github.com/user-attachments/assets/2bb8dabb-e03e-455a-8dd2-433e977a1b00">
