### ISSUE TITLE
General Question About Tag Limits When Using Open Source South Bound Protocols

### ISSUE THREAD

**Issue by GripenANM** [emqx/neuron#2351]
Just a quick question about the tag and node limits for neuron. When downloading the complied version from GitHub release, I found that the trial license and commercial plugins came preinstalled. When using open source protocols such as Modbus TCP and RTU, I realized the number of tags is still counted towards the license which is different that what is stated in the read me. If I am not mistaken, the amount of tags for open source protocols should be unlimited? If this is the commercial version in the github release, how can install the open source version that does not come with tag limits or commercial plugins preinstalled? 

If someone can help clarify, this would be highly appreciated. 

Version: neuron-2.10.1-linux-amd64
Neuron-Dashboard: 2.4.9

![image](https://github.com/user-attachments/assets/636239c5-be6a-4e71-ba4e-21cb8ecfbe6b)
![image](https://github.com/user-attachments/assets/f95bf04a-abb1-407b-a998-42e55ceb7c27)
![image](https://github.com/user-attachments/assets/32be117d-9498-4be3-9e4d-1a885dfed58a)
![image](https://github.com/user-attachments/assets/ab076a76-8b2d-48de-a04c-5154f4b470f5)

**Comment by fengzeroz** [comment]
Only by using neuron source to compile it yourself, there be no license restrictions.
