### ISSUE TITLE
Report 404 when trying to download the latest version

### ISSUE THREAD

**Issue by xyfabc** [emqx/neuron#463]
![图片](https://user-images.githubusercontent.com/13639600/167058320-594a4e58-aece-4a1e-bf41-f859869e12f2.png)

**Comment by gc87** [comment]
The release version of this repository does not provide the front-end package, please go to the [official website](https://neugates.io/) to download the full installation package.

**Comment by lixiumei123** [comment]
Front-end interface installation steps：
* Download the tar.gz package for Linux from the official website：
`$ wget https://www.emqx.com/zh/downloads/neuron/2.0.1/neuron-2.0.1-linux-amd64.tar.gz`
* Unpack the tar.gz package:
`$ tar -zxvf neuron-2.0.1-linux-amd64.tar.gz`
* Go to the extracted folder:
`$ cd neuron-2.0.1-linux`
* Copy the dist folder to the bottom of the neuron/build
`$ cp -r dist ${path}/neuron/build`

_notes:_ Choice of CPU architecture

**Comment by fengzeroz** [comment]
We are aready considering including dashboard in release.
