### ISSUE TITLE
Error linking libneuron-base——relocation R_X86_64_PC32 against symbol `mqtt_fixed_header_rules' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by wlq965** [emqx/neuron#477]
/usr/bin/ld: /usr/local/lib/libmqttc.a(mqtt.c.o): relocation R_X86_64_PC32 against symbol `mqtt_fixed_header_rules' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: last link failed: bad value
collect2: error: ld returned 1 exit status

**Comment by hobbes1069** [comment]
I ran into the same problem. This should really be reported to the MQTT-C project to turn on PIC by default.

**Comment by gc87** [comment]
When compiling libmqtt-c deps, you need to turn on the -fPIC option. To do this, you can add `set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" -fPIC)` in CMakeLists.txt of mqtt-c project or add `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` in camke parameters.

**Comment by gc87** [comment]
MQTT-C has enabled -fPIC compilation by default.
https://github.com/LiamBindle/MQTT-C/pull/166
