### ISSUE TITLE
CMake Error at CMakeLists.txt:74 (find_package):

### ISSUE THREAD

**Issue by ihxzihxz** [emqx/neuron#527]
CMake Error at CMakeLists.txt:74 (find_package):
  Could not find a package configuration file provided by "nng" with any of
  the following names:

    nngConfig.cmake
    nng-config.cmake

  Add the installation prefix of "nng" to CMAKE_PREFIX_PATH or set "nng_DIR"
  to a directory containing one of the above files.  If "nng" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by gc87** [comment]
Refer to the documentation below to install the dependent libraries
https://github.com/emqx/neuron/blob/main/Install-dependencies.md
