### ISSUE TITLE
Assertion `adapter->plugin_info.plugin != NULL' failed

### ISSUE THREAD

**Issue by Liangzx** [emqx/neuron#542]
my system info:  UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
when i use neuron-2.0.1-linux-amd64.tar.gz
and run ./neuron
it failed:
/home/runner/work/neuron/neuron/src/adapter/adapter.c:1385: neu_adapter_create: Assertion `adapter->plugin_info.plugin != NULL' failed.

**Comment by Liangzx** [comment]
this because i run it

**Comment by catch6** [comment]
> my system info: UTC 2022 x86_64 x86_64 x86_64 GNU/Linux when i use neuron-2.0.1-linux-amd64.tar.gz and run ./neuron it failed: /home/runner/work/neuron/neuron/src/adapter/adapter.c:1385: neu_adapter_create: Assertion `adapter->plugin_info.plugin != NULL' failed.

@Liangzx 你最后咋解决的
