### ISSUE TITLE
Assertion `adapter->plugin_info.plugin != NULL` failed in v2.0.1 release package

### ISSUE THREAD

**Issue by gc87** [emqx/neuron#543]
![98041017-d129-4527-b628-a4ba30a9e53d](https://user-images.githubusercontent.com/8831188/173769539-5afecb04-ee2c-4088-8056-e4764a88d63e.png)

**Comment by Liangzx** [comment]
> Please check whether another NEURON instance is running in the system, and also check whether ports 7000 and 7001 have been used (NEURON runs under ports 7000 and 7001).

yes i run a instance with a docker , thank you !!!
