### ISSUE TITLE
neuron2.0.1 dashborad south refresh error

### ISSUE THREAD

**Issue by chq24707** [emqx/neuron#634]
System: XuanTie 21.06 (kaitai)
Architecture: armv7l
Description: In the test of 3000 points, the acquisition frequency is 100ms. When the number of drives is too large, resulting in the error of the South refresh of the front end of the neuron, for example: 100 drives, 30 points under each drive, and the acquisition frequency is 100ms, the following errors will appear:
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/97088188/178447772-5ad38194-730b-43f2-a40a-39cc31082b2d.png">
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/97088188/178448945-66d85789-7e01-4e52-af5d-7cefc31b0309.png">

CPU and memory usage：
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/97088188/178448599-0cc573fb-05e4-408a-a018-8065ce3040bf.png">

**Comment by fengzeroz** [comment]
The default buf size of nng is small, and an error will be reported directly when there are many concurrent requests.

**Comment by fengzeroz** [comment]
#653
