### ISSUE TITLE
Neuron can't read the value of the tag.

### ISSUE THREAD

**Issue by chengbaifangyun123** [emqx/neuron#651]
Version: open source
Question: Can't read the value of the tag.
![2](https://user-images.githubusercontent.com/10191288/179493173-cde39de6-0c59-4c48-90e8-a10c5fde91ca.jpg)

**Comment by chengbaifangyun123** [comment]
![官方镜像南向设备的状态返回值](https://user-images.githubusercontent.com/10191288/180357352-6c0bc045-83d7-4242-994c-f694bbccfecc.jpg)
![开源版南向设备的状态返回值](https://user-images.githubusercontent.com/10191288/180357360-c36046e8-6608-4ce5-9dc3-b91e2de86e46.jpg)

**Comment by chengbaifangyun123** [comment]
是因为南向设备这个link状态的值不对，没连成功才会导致读取不到这个南向设备的数据

**Comment by lixiumei123** [comment]
It's not that the value of link is wrong, is your localhost in the same segment as the modbus simulator's ip?

**Comment by lixiumei123** [comment]
The open source version doesn't support such a configuration.
![modbus-tcp](https://user-images.githubusercontent.com/82565631/180375528-08f03982-568e-457d-b1ff-33bd86c6b67c.png)
