### ISSUE TITLE
post /api/v2/node/setting with wrong scene

### ISSUE THREAD

**Issue by 0perhaps** [emqx/neuron#721]
通过请求api的方式去配置mqtt的北向设备过程中，heartbeat-topic没有传，虽然返回结果并没有报错，但是其它参数也没有设置成功。
翻译（translate）：
In the process of configuring the northbound device of mqtt by requesting api, the heartbeat-topic was not transmitted. Although the returned result did not report an error, other parameters were not set successfully.

**Comment by gc87** [comment]
Fixed by pr #734
