### ISSUE TITLE
post /api/v2/node/setting with wrong scene 2

### ISSUE THREAD

**Issue by 0perhaps** [emqx/neuron#730]
在已创建的南向modbus-rtu协议设备上进行配置时，根据客户端页面查看配置并没有host和port参数。然后通过接口请求时发现。如果没带上参数host和port参数，会导致部分参数配置失效。但是接口请求并无报错，为正常返回结果。
实际场景中验证了下发参数中没有带上host和port参数会导致device参数配置失败，仅针对于modbus-rtu协议的南向设备。
翻译：
When configuring on the created southbound modbus-rtu protocol device, according to the configuration on the client page, there are no host and port parameters. Then it is found when requested through the interface. If the parameter host and port parameters are not included, some parameter configurations will be invalid. However, there is no error in the interface request, and the result is returned normally.
In the actual scenario, it has been verified that the host and port parameters are not included in the delivered parameters, which will cause the device parameter configuration to fail. This is only for southbound devices of the modbus-rtu protocol.

**Comment by lixiumei123** [comment]
The client page modbus-rtu supports two connection methods: serial port and tcp. For the api configuration method, please refer to [Plugin Settings](https://neugates.io/docs/zh/latest/reference/plugin-setting.html#modbus).
