### ISSUE TITLE
neuron doesn't support function codes 0x06 and 0x0F, and does not fully support standard modbus, resulting  in poor compatibility and unusable in many scenarios.

### ISSUE THREAD

**Issue by Jimmy-Wen** [emqx/neuron#806]
Description: 0x06 and 0x0f are modbus standard function codes, neuron does not fully support standard modbus, resulting in very limited application scenarios.
For example, Huawei inverters, Jinlang inverters, and other mainstream manufacturers of inverters all support function code 0x06 to write a single holding register;

**Comment by lixiumei123** [comment]
Thank you for pointing out the problem. We will add these two function codes, but Neuron supports 0x05 and 0x11 function codes, which can also write registers and write coils to the device.
