### ISSUE TITLE
Does the opc shift component provide a trial？

### ISSUE THREAD

**Issue by iqihao** [emqx/neuron#820]
Does the opcshift component provide a trial？

**Comment by gc87** [comment]
Yes, but the official download link has not been provided yet, I uploaded it in the attachment of this issue.
[opcshift.zip](https://github.com/emqx/neuron/files/9670527/opcshift.zip)
It might be helpful to read [here](https://neugates.io/docs/en/latest/module-plugins/module-driver.html#opcda)

**Comment by iqihao** [comment]
> Yes, but the official download link has not been provided yet, I uploaded it in the attachment of this issue. [opcshift.zip](https://github.com/emqx/neuron/files/9670527/opcshift.zip) It might be helpful to read [here](https://neugates.io/docs/en/latest/module-plugins/module-driver.html#opcda)

thanks
