### ISSUE TITLE
Northbound MODBUS (TCP / serial RTU)

### ISSUE THREAD

**Issue by oori** [emqx/neuron#830]
Here's the current [northbound plugin modules](https://neugates.io/docs/en/latest/module-plugins/module-list.html#northbound-plugin-modules).

What's the best approach to develop a plugin for a scenario, where the unit acts **also** as a MODBUS server, ie. other MODBUS clients (or SCADA) query metrics from it.  Polling-based northbound communication.

Thanks.

**Comment by fengzeroz** [comment]
Northbound does not support protocols such as Modbus

**Comment by oori** [comment]
Ok, thanks for the reply.
