### ISSUE TITLE
[Driver Configuration] The tag-list page does not list all tag's configuration information (such as precision, decimal).

### ISSUE THREAD

**Issue by Jimmy-Wen** [emqx/neuron#860]
The precision and decimal are not displayed, which can only be seen in the editing interface, which is inconvenient.

[ tag页面并没有列出所有属性，精度和乘系数两个属性自动被隐藏掉，只有点击编辑操作才能查看，有点不太方便。]

![1666676842983](https://user-images.githubusercontent.com/44196699/197692949-b368837f-0b10-4ee8-ad45-f69c61f9590e.png)

**Comment by lixiumei123** [comment]
We will consider adding it later, thank you for your suggestion.

**Comment by lixiumei123** [comment]
Will be supported in version 2.3.0.
