### ISSUE TITLE
How to package and run my own compiled files in my pi?

### ISSUE THREAD

**Issue by zhouzaihang** [emqx/neuron#950]
Why did you remove the ci of package deb?
Or could you share your Dockerfile in emqx/neuron(Docker hub)?

**Comment by eeff** [comment]
The repo has a script `package-sdk.sh` which could be used to produce a tarbar, you may have a look.

**Comment by zhouzaihang** [comment]
> The repo has a script `package-sdk.sh` which could be used to produce a tarbar, you may have a look.

Not package sdk, and we want to package deb or rmp.
And I remember the repo had script in folds of packages.

**Comment by eeff** [comment]
> > The repo has a script `package-sdk.sh` which could be used to produce a tarbar, you may have a look.
> 
> Not package sdk, and we want to package deb or rmp. And I remember the repo had script in folds of packages.

If you make a tarbar using `package-sdk.sh` then it's easy to build your own docker images.
As for deb/rpm packages, you may consult the deb/rpm documentaion. And if you interested, run ` git log -p package ` to see the scripts.

**Comment by zhouzaihang** [comment]
ok
